const Xprz = require("xprz");
Xprz.Package().dotenv().setupDot();
const { use, launch, loadRoutes, useJsonBody, static } = Xprz.App();
launch();
useJsonBody();
static("public");
const cookieParser = $install("cookie-parser");
use(cookieParser());
$read("middleware/setup");
$read("utils/database");
loadRoutes("routes");
