// Import your header component function here
import Header from "./components/header.js"; // Adjust the path as necessary

// Function to insert the header into the DOM
function insertHeader() {
  // Find the header container element in the DOM
  const headerContainer = document.querySelector("header");

  // Check if the header container element exists
  if (headerContainer) {
    // Replace the content of the header container with the HTML content generated by the Header component
    headerContainer.innerHTML = Header();
  }
}

// Call the insertHeader function when the DOM content is loaded
document.addEventListener("DOMContentLoaded", insertHeader());
